### ISSUE TITLE
webpack:devServerUrl not respecting other run configurations

### ISSUE THREAD

**Issue by MagneH** [fortedigital/EpiCommonUtils#8]
The tool is picking webpack:devServerUrl from Web.config, disregarding the run configuration being used (Web.Dev.config, Web.Debug.config etc.. ). This causes trouble with version control, when developers forget to set it back to localhost before commiting their local changes. 

@tomaszmadeyski @mgrzyb @zbigniewwiniarski

**Comment by tomaszmadeyski** [comment]
hmm, I'm not sure if I understand. 

`Web.Dev.config`, `Web.Debug.config` are just transformation files which are not taken under consideration at runtime. So, correct me if I'm wrong, everything which is in `Web.Debug.config` is ignored at runtime, so is `webpack:devServerUrl`. 
In order to get values from `Web.Dev.config` you need to somehow run those transformations, which are usually run during build time at your Continous Integration pipeline.

However, there's this trick which might do the job for you. In your web.config add `file` attribute to `<appSettings>` section like this:

```
<appSettings file="Web.AppSettings.LocalDev.config">
  <add key="webpack:devServerUrl" value="A"/>
</appSettings>
```

now, add a flle `Web.AppSettings.LocalDev.config` with whatever overriden values you like
```
<?xml version="1.0" encoding="utf-8"?>
<appSettings>
  <add key="webpack:devServerUrl" value="B"/>  
</appSettings>
```

and add this file to `.gitignore` which will solve your issues with version control.

This should make your ConfigurationManager to get `B` as a value of `webpack:devServerUrl`

Note: Remember to add transformation (most probably `Web.Release.config` which will remove `file` attribute from `<appSettings>` section
